Started by user [8mha:////4BMGkg3j4zNuSbeulW5IjFjaD1nGIqcqfegRoL5kSA3FAAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzWEgZu/dLi1CL9xJTczDwAj6GcLcAAAAA=[0mFatih
Running as SYSTEM
Building in workspace /var/jenkins_home/workspace/docker-job
[8mha:////4AQUz049CopEKxEO/Qtrj0bOBHqRWoMXMKIEoQ2m2uV0AAAAqx+LCAAAAAAAAP9b85aBtbiIQSujNKU4P0+vIKc0PTOvWC8xrzgzOT8nv0gvMbkkEyjhCKb88ktSdwVsu2efuqidiYHRh4EDIu2ZUsIg5JOVWJaon5OYl64fXFKUmZduXVHEIAU1ODk/rzg/J1XPGUKDDGKAAEYmBoaKghIGlWSTFKNkM6NUXfMkA3Ndk1TLRF1LC2Nz3VQTAzNjkyQTc2MDMwAMIOMTrwAAAA==[0m[docker-job] $ ansible-playbook /var/jenkins_home/ansible/docker.yml -i /var/jenkins_home/ansible/hosts -f 5 -e "MSG='Guys you are amazing'"
/usr/local/lib/python3.5/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
  from cryptography.exceptions import InvalidSignature

PLAY [test1] *******************************************************************

TASK [Gathering Facts] *********************************************************
[0;32mok: [test1][0m

TASK [debug] *******************************************************************
[0;32mok: [test1] => {[0m
[0;32m    "msg": "Guys you are amazing"[0m
[0;32m}[0m

PLAY RECAP *********************************************************************
[0;32mtest1[0m                      : [0;32mok=2   [0m changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Finished: SUCCESS
